# coding: utf-8
import pandas as pd
import pickle
df = pd.DaraFrame(pickle.load(open('/data/dummied_recent_data.pkl', 'rb')))
df = pd.DataFrame(pickle.load(open('/data/dummied_recent_data.pkl', 'rb')))
df = pd.DataFrame(pickle.load(open('data/dummied_recent_data.pkl', 'rb')))
df.head[:5]
df.head(n=5)
print list(df)
df2 = pd.DataFrame(pickle.load(open('data/cleaned_data_with_features.pkl', 'rb')))
print list(df2)
print list(df)
print list(df2)
df2 = pd.DataFrame(pickle.load(open('data/cleaned_data_with_features.pkl', 'rb')))
print list(df2)
df = pd.DataFrame(pickle.load(open('data/dummied_recent_data.pkl', 'rb')))
print list(df)
df = pd.DataFrame(pickle.load(open('data/dummied_recent_data.pkl', 'rb')))
print list(df)
df2 = pd.DataFrame(pickle.load(open('data/cleaned_data_with_features.pkl', 'rb')))
print list(df2)
df = pd.DataFrame(pickle.load(open('data/dummied_recent_data.pkl', 'rb')))
print list(df)
df2 = pd.DataFrame(pickle.load(open('data/cleaned_data_with_features.pkl', 'rb')))
print list(df2)
df = pd.DataFrame(pickle.load(open('data/dummied_recent_data.pkl', 'rb')))
print list(df)
df3 = pd.DataFrame(pickle.load(open('dummied_full_data.pkl', 'rb')))
df3 = pd.DataFrame(pickle.load(open('data/dummied_full_data.pkl', 'rb')))
print list(df3)
df3 = pd.DataFrame(pickle.load(open('data/dummied_full_data.pkl', 'rb')))
print list(df3)
df3.shape
df4 = pd.DataFrame(pickle.load(open('data/read_score.pkl'', 'rb')))
df4 = pd.DataFrame(pickle.load(open('data/read_score.pkl', 'rb')))
print list(df4)
df4.head(n=5)
df5 = pd.DataFrame(pickle.load(open('data/polar_score.pkl', 'rb')))
print list(df5)
df5.head(n=5)
